---
config:
  theme: neo-dark
---
flowchart TB
    A["Your IDE"] L_A_B_0@--> B["optidevdoc-remote.js"]
    B L_B_C_0@--> C["HTTPS API"] & A
    C L_C_D_0@--> D["Render.com Server"] & B
    D L_D_E_0@--> E["Optimizely Docs"] & C
    E L_E_D_0@--> D
    L_A_B_0@{ animation: slow } 
    L_B_C_0@{ animation: slow } 
    L_B_A_0@{ animation: slow } 
    L_C_D_0@{ animation: slow } 
    L_C_B_0@{ animation: slow } 
    L_D_E_0@{ animation: slow } 
    L_D_C_0@{ animation: slow } 
    L_E_D_0@{ animation: slow }
